server:
  port: 9090

book:
  name: java
  author: 岳家瑞

logging:
  level:
    root: debug




#spring:
#  profiles:
#    active: dev

spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    password: yuejiarui
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false

